# Generated by Django 3.0.4 on 2020-04-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MS_list',
            fields=[
                ('Itemname', models.CharField(max_length=50)),
                ('Itemcode', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=20)),
                ('isapprovedbydphead', models.BooleanField(default=False)),
                ('isapprovedbysupervisor', models.BooleanField(default=False)),
                ('isapprovedbystoreman', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Departmentname', models.CharField(max_length=50)),
                ('Departmentcode', models.IntegerField(primary_key=True, serialize=False)),
                ('Budjet_alloted_peryear', models.FloatField()),
                ('Budjet_remained', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_code', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Order')),
            ],
        ),
    ]
